### ISSUE TITLE
Problem running mongodb commands

### ISSUE THREAD

**Issue by jvence** [feelinc/apache-nutch-mongo-docker#1]
Followed your instructions and typed: docker exec -it mongo admin
but I get the following error:
Error response from daemon: No such container: mongo

Tried docker exec apachenutchmongodockermaster_mongo_1 mongo admin instead, and it just sits there

**Comment by feelinc** [comment]
Try : 
`docker ps -a`
Then find the correct CONTAINER ID for the mongo:3.3.6, then run below command:
`docker exec -it <container_id> /bin/bash`
Then run below command to get into the mongo shell :
`mongo`
